spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul
    username: root
    password: Tmxk1315()!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true